@host = http://localhost
@port = 5261
@Employees.Web_HostAddress = {{host}}:{{port}}

GET {{Employees.Web_HostAddress}}/weatherforecast/
Accept: application/json
ProjectUrl: {{$projectUrl}}
Guid: {{$guid}}
LocaleDate: {{$datetime iso8601}}
Random-int: {{$randomInt}}

###
